name:  OpenDevOps-ES
description: |
   Elasticsearch Docker Image for Logging Server
version:  1.0.0
category:  LOG 
maintainer:  open.devops
license:  Apache 2
projectURL: https://github.com/ open-devops/docker-log-es 
